/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Master handler for getting a variables name, short name, etc.
*/
params [["_var", "", [""]], ["_mode", -1, [0]]];
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "joint": {"life_inv_joint"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "fishing": {"life_inv_fishingpoles"};
			case "coffee": {"life_inv_coffee"};
			case "turtlesoup": {"life_inv_turtlesoup"};
			case "donuts": {"life_inv_donuts"};
			case "fuelE": {"life_inv_fuelE"};
			case "fuelF": {"life_inv_fuelF"};
			case "money": {"life_cash"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "iron_r": {"life_inv_ironr"};
			case "copper_r": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "salt_r": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondr"};
			case "cocaine": {"life_inv_coke"};
			case "cocainep": {"life_inv_cokep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "goldbar": {"life_inv_goldbar"};
			case "blastingcharge": {"life_inv_blastingcharge"};
			case "boltcutter": {"life_inv_boltcutter"};
			case "defusekit": {"life_inv_defusekit"};
			case "storagesmall": {"life_inv_storagesmall"};
			case "storagebig": {"life_inv_storagebig"};
			case "goldbarp": {"life_inv_goldbarp"};
			case "underwatercharge": {"life_inv_underwatercharge"};
			case "rye": {"life_inv_rye"};
			case "hops": {"life_inv_hops"};
			case "yeast": {"life_inv_yeast"};
			case "cornmeal": {"life_inv_cornmeal"};
			case "moonshine": {"life_inv_moonshine"};
			case "bottles": {"life_inv_bottles"};
			case "bottledshine": {"life_inv_bottledshine"};
			case "bottledbeer": {"life_inv_bottledbeer"};
			case "bottledwhiskey": {"life_inv_bottledwhiskey"};
			case "beerp": {"life_inv_beerp"};
			case "whiskey": {"life_inv_whiskey"};
			case "mash": {"life_inv_mash"};
			case "kabelbinder":{"life_inv_kabelbinder"};
			case "absperrung":{"life_inv_absperrung"};
			case "strahler":{"life_inv_strahler"};
			case "tapesign":{"life_inv_tapesign"};
			case "pole":{"life_inv_pole"};
			case "huetchen":{"life_inv_huetchen"};
			case "battery": {"life_inv_battery"};
			case "puranium": {"life_inv_puranium"};
			case "ipuranium": {"life_inv_ipuranium"};
			case "uranium1": {"life_inv_uranium1"};
			case "uranium2": {"life_inv_uranium2"};
			case "uranium3": {"life_inv_uranium3"};
			case "uranium4": {"life_inv_uranium4"};
			case "uranium": {"life_inv_uranium"};
			case "spritze": {"life_inv_spritze"};
			case "fisch": {"life_inv_fisch"};
			case "dirt": {"life_inv_dirt"};
			case "papier": {"life_inv_papier"};
			case "ptuete": {"life_inv_ptuete"};
			case "stiefel": {"life_inv_stiefel"};
			case "ssenkel": {"life_inv_ssenkel"};
			case "hoffnung": {"life_inv_hoffnung"};
			case "glasflasche": {"life_inv_glasflasche"};
			case "bolzen": {"life_inv_bolzen"};
			case "gschaft": {"life_inv_gschaft"};
			case "feder": {"life_inv_feder"};
			case "spulver": {"life_inv_spulver"};
			case "abzug": {"life_inv_abzug"};
			case "glauf": {"life_inv_glauf"};
			case "vhalterung": {"life_inv_vhalterung"};
			case "schrauben": {"life_inv_schrauben"};
			case "plauf": {"life_inv_plauf"};
			case "schmuck": {"life_inv_schmuck"};
			case "sfetzen": {"life_inv_sfetzen"};
			case "nadel": {"life_inv_nadel"};
			case "gfaden": {"life_inv_gfaden"};
			case "rfaden": {"life_inv_rfaden"};
			case "ofaden": {"life_inv_ofaden"};
			case "sfaden": {"life_inv_sfaden"};
			case "cstoff": {"life_inv_cstoff"};
			case "rsfetzen": {"life_inv_rsfetzen"};
			case "bsfetzen": {"life_inv_bsfetzen"};
			case "blynx1": {"life_inv_blynx1"};
			case "blynx2": {"life_inv_blynx2"};
			case "blynx3": {"life_inv_blynx3"};
			case "blrr1": {"life_inv_blrr1"};
			case "blrr2": {"life_inv_blrr2"};
			case "btitan1": {"life_inv_btitan1"};
			case "btitan2": {"life_inv_btitan2"};
			case "bzafir": {"life_inv_bzafir"};
			case "sflasche": {"life_inv_sflasche"};
			case "npren": {"life_inv_npren"};
			case "pflasche": {"life_inv_pflasche"};
			case "axe": {"life_inv_axe"};
			case "wood": {"life_inv_wood"};
			case "woodc": {"life_inv_woodc"};
			case "woodi": {"life_inv_woodi"};
			case "pat" : {"life_inv_pat"};
			case "al" : {"life_inv_al"};
			case "patg": {"life_inv_patg"};
			case "fuelPipe": {"life_inv_fuelPipe"};
			case "speedbomb": {"life_inv_speedbomb"};

		};
	};

	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_fishingpoles": {"fishing"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_turtlesoup": {"turtlesoup"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelF": {"fuelF"};
			case "life_inv_fuelE": {"fuelE"};
			case "life_cash": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"iron_r"};
			case "life_inv_copperr": {"copper_r"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondr": {"diamondc"};
			case "life_inv_saltr": {"salt_r"};
			case "life_inv_coke": {"cocaine"};
			case "life_inv_cokep": {"cocainep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_blastingcharge": {"blastingcharge"};
			case "life_inv_boltcutter": {"boltcutter"};
			case "life_inv_defusekit": {"defusekit"};
			case "life_inv_storagesmall": {"storagesmall"};
			case "life_inv_storagebig": {"storagebig"};
			case "life_inv_goldbarp": {"goldbarp"};
			case "life_inv_underwatercharge": {"underwatercharge"};
			case "life_inv_mash": {"mash"};
			case "life_inv_yeast": {"yeast"};
			case "life_inv_rye": {"rye"};
			case "life_inv_hops": {"hops"};
			case "life_inv_whiskey": {"whiskey"};
			case "life_inv_beerp": {"beerp"};
			case "life_inv_bottles": {"bottles"};
			case "life_inv_cornmeal": {"cornmeal"};
			case "life_inv_bottledwhiskey": {"bottledwhiskey"};
			case "life_inv_bottledbeer": {"bottledbeer"};
			case "life_inv_bottledshine": {"bottledshine"};
			case "life_inv_moonshine": {"moonshine"};
			case "life_inv_kabelbinder": {"kabelbinder"};
			case "life_inv_absperrung":{"absperrung"};
			case "life_inv_strahler":{"strahler"};
			case "life_inv_pole":{"pole"};
			case "life_inv_tapesign":{"tapesign"};
			case "life_inv_huetchen":{"huetchen"};
			case "life_inv_battery": {"battery"};
			case "life_inv_puranium": {"puranium"};
			case "life_inv_ipuranium": {"ipuranium"};
			case "life_inv_uranium1": {"uranium1"};
			case "life_inv_uranium2": {"uranium2"};
			case "life_inv_uranium3": {"uranium3"};
			case "life_inv_uranium4": {"uranium4"};
			case "life_inv_uranium": {"uranium"};
			case "life_inv_joint": {"joint"};
			case "life_inv_spritze": {"spritze"};
			case "life_inv_fisch": {"fisch"};
			case "life_inv_dirt": {"dirt"};
			case "life_inv_papier": {"papier"};
			case "life_inv_ptuete": {"ptuete"};
			case "life_inv_stiefel": {"stiefel"};
			case "life_inv_ssenkel": {"ssenkel"};
			case "life_inv_hoffnung": {"hoffnung"};
			case "life_inv_glasflasche": {"glasflasche"};
			case "life_inv_bolzen": {"bolzen"};
			case "life_inv_gschaft": {"gschaft"};
			case "life_inv_feder": {"feder"};
			case "life_inv_spulver": {"spulver"};
			case "life_inv_abzug": {"abzug"};
			case "life_inv_glauf": {"glauf"};
			case "life_inv_vhalterung": {"vhalterung"};
			case "life_inv_schrauben": {"schrauben"};
			case "life_inv_plauf": {"plauf"};
			case "life_inv_schmuck": {"schmuck"};
			case "life_inv_sfetzen": {"sfetzen"};
			case "life_inv_nadel": {"nadel"};
			case "life_inv_gfaden": {"gfaden"};
			case "life_inv_rfaden": {"rfaden"};
			case "life_inv_ofaden": {"ofaden"};
			case "life_inv_sfaden": {"sfaden"};
			case "life_inv_cstoff": {"cstoff"};
			case "life_inv_rsfetzen": {"rsfetzen"};
			case "life_inv_bsfetzen": {"bsfetzen"};
			case "life_inv_blynx1": {"blynx1"};
			case "life_inv_blynx2": {"blynx2"};
			case "life_inv_blynx3": {"blynx3"};
			case "life_inv_blrr1": {"blrr1"};
			case "life_inv_blrr2": {"blrr2"};
			case "life_inv_btitan1": {"btitan1"};
			case "life_inv_btitan2": {"btitan2"};
			case "life_inv_bzafir": {"bzafir"};
			case "life_inv_npren": {"npren"};
			case "life_inv_sflasche": {"sflasche"};
			case "life_inv_pflasche": {"pflasche"};
			case "life_inv_axe": {"axe"};
			case "life_inv_wood": {"wood"};
			case "life_inv_woodc": {"woodc"};
			case "life_inv_woodi": {"woodi"};
			case "life_inv_pat": {"pat"};
			case "life_inv_al" : {"al"};
			case "life_inv_patg": {"patg"};
			case "life_inv_fuelPipe": {"fuelPipe"};
			case "life_inv_speedbomb": {"speedbomb"};
	};
	};
};
